# Filepath to certs repository
CertsRepo = './root/ca/intermediate/certs/'
# Filepath to csr repository
CsrRepo = './root/ca/intermediate/csr/'
# Filepath to cert (chain) file
CertChain = './root/ca/intermediate/certs/ca-chain.cert.pem'
