name: Run Tests on Pull Request
run-name: ${{ github.actor }} is making a pull request
on:
  pull_request:
    branches:
    - main

jobs:
  Run-Go-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go Test
        uses: robherley/go-test-action@v0.4.1
