name: Pull Request Tests
run-name: ${{ github.actor }} is making a pull request
on:
  pull_request:
    branches:
    -  main

jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go environment
        uses: actions/setup-go@v5

      - name: Run unit tests
        uses: robherley/go-test-action@v0.4.1
